CREATE TABLE SmallSize (
	Id STRING(MAX) NOT NULL,
	CommitedAt TIMESTAMP OPTIONS (allow_commit_timestamp=true),
	Content STRING(MAX) NOT NULL,
	CreatedAt TIMESTAMP NOT NULL,
	UpdatedAt TIMESTAMP NOT NULL,
) PRIMARY KEY (Id)